// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KtabiTest.Model
{
    public partial class Classes
    {
        public Classes()
        {
            CourseAppointment = new HashSet<CourseAppointment>();
        }

        public int ClassId { get; set; }
        public string ClassName { get; set; }

        public virtual ICollection<CourseAppointment> CourseAppointment { get; set; }
    }
}