// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KtabiTest.Model
{
    public partial class Courses
    {
        public Courses()
        {
            CourseAppointment = new HashSet<CourseAppointment>();
        }

        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int NumberOfhours { get; set; }
        public int NumberOflectures { get; set; }

        public virtual ICollection<CourseAppointment> CourseAppointment { get; set; }
    }
}