// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KtabiTest.Model
{
    public partial class Student
    {
        public int StudentId { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public string WorkInformation { get; set; }
        public string ChurchName { get; set; }

        public virtual StudentName StudentNavigation { get; set; }
    }
}