// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KtabiTest.Model
{
    public partial class StudentPhoneNumber
    {
        public int StudentId { get; set; }
        public string PhoneNumber { get; set; }
        public string HomeNumber { get; set; }
        public string Phonenumber2 { get; set; }

        public virtual StudentName Student { get; set; }
    }
}