// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KtabiTest.Model
{
    public partial class StudentName
    {
        public StudentName()
        {
            StudentCourse = new HashSet<StudentCourse>();
        }

        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string FourthName { get; set; }

        public virtual Student Student { get; set; }
        public virtual StudentPhoneNumber StudentPhoneNumber { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
    }
}