// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KtabiTest.Model
{
    public partial class StudentCourse
    {
        public int? CourseId { get; set; }
        public int? StudentId { get; set; }
        public decimal? ElBa2i { get; set; }
        public DateTime? PayDate { get; set; }
        public string ElTwki3 { get; set; }
        public string Notes { get; set; }
        public int Id { get; set; }
        public decimal? ElMdfo3 { get; set; }

        public virtual CourseAppointment Course { get; set; }
        public virtual StudentName Student { get; set; }
    }
}